# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TeGusVRAOJZAhmEbSjv5iHoDGtfiz2Q

**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.namespace import RDF, RDFS
owl = Namespace("http://www.w3.org/2002/07/owl#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

for s1 in g1.subjects(RDF.type, None):
  given1 = next(g1.objects(s1, vcard.Given), None)
  family1=next(g1.objects(s1, vcard.Family), None)
  if given1 and family1:
    for s2 in g2.subjects(RDF.type, None):
      given2 = next(g2.objects(s2, vcard.Given), None)
      family2 = next(g2.objects(s2, vcard.Family), None)
      if given2 and family2:
        if str(given1) == str(given2) and str(family1) == str(family2):
          g3.add((s1, owl.sameAs, s2))

for s, p, o in g3:
  print(s, p, s)