# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13psLr0xZv7Y04g2XaBkB3w7iity008RI

**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

from rdflib.namespace import RDF, RDFS

vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
data = Namespace("http://data.org#")

g1.namespace_manager.bind('vcard', vcard)
g1.namespace_manager.bind('data', data)
g2.namespace_manager.bind('vcard', vcard)
g2.namespace_manager.bind('data', data)

for s in g1.subjects(RDF.type, data.Person):
  print (s)

for person in g1.subjects(RDF.type, data.Person):
    if not g1.value(person, vcard.Given):
        nombre = g2.value(person, vcard.Given)
        if nombre:
            g1.add((person, vcard.Given, nombre))
    if not g1.value(person, vcard.Family):
        apellido = g2.value(person, vcard.Family)
        if apellido:
            g1.add((person, vcard.Family, apellido))
    if not g1.value(person, vcard.EMAIL):
        email = g2.value(person, vcard.EMAIL)
        if email:
            g1.add((person, vcard.EMAIL, email))

for s, p, o in g1:
  print(s,p,o)