# -*- coding: utf-8 -*-
"""Task09.ipynb
Automatically generated by Colab.
**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.namespace import OWL
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")

people_g1 = {}
people_g2 = {}

# Recorremos g1
for person in g1.subjects():
    nick = None
    family = None
    for n in g1.objects(person, foaf.nick):
        nick = str(n)
    for f in g1.objects(person, vcard.Family):
        family = str(f)
    if nick and family:
        people_g1[(nick, family)] = person

# Recorremos g2
for person in g2.subjects():
    nick = None
    family = None
    for n in g2.objects(person, foaf.nick):
        nick = str(n)
    for f in g2.objects(person, vcard.Family):
        family = str(f)
    if nick and family:
        people_g2[(nick, family)] = person

for key in people_g1:
    if key in people_g2:
        g3.add((people_g1[key], OWL.sameAs, people_g2[key]))

