# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bG3Xoa-8u_Vqs_agbCbs1K20aGgBxTky

**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

DATA = Namespace("http://data.org#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

personas_g1 = []

for s, p, o in g1:
    if str(o) == "http://data.org#Person":
        if s not in personas_g1:
            personas_g1.append(s)


for persona in personas_g1:
    #Que inf tenemos en g1??
    given_g1 = None
    family_g1 = None
    email_g1 = None

    for s, p, o in g1:
        if s == persona:
            if p == VCARD.Given:
                given_g1 = o
            elif p == VCARD.Family:
                family_g1 = o
            elif p == VCARD.EMAIL:
                email_g1 = o

    print("  Información en data01.rdf:")
    print(f"    Given name: {given_g1 if given_g1 else 'FALTA'}")
    print(f"    Family name: {family_g1 if family_g1 else 'FALTA'}")
    print(f"    Email: {email_g1 if email_g1 else 'FALTA'}")

    given_g2 = None
    family_g2 = None
    email_g2 = None

    for s, p, o in g2:
        if s == persona:
            if p == VCARD.Given:
                given_g2 = o
            elif p == VCARD.Family:
                family_g2 = o
            elif p == VCARD.EMAIL:
                email_g2 = o


    if given_g1:
      given_final = given_g1
    else: given_final = given_g2
    if family_g1:
      family_final = family_g1
    else: family_final = family_g2
    if email_g1:
      email_final = email_g1
    else: email_final = email_g2



    print(f"  INFORMACIÓN COMPLETA DE LO ANTERIOR:")
    print(f"    Given name: {given_final}")
    print(f"    Family name: {family_final}")
    print(f"    Email: {email_final}")