# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169M_xv5ftBiErN_KfIMMZIae0xG0oWZj

**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

#Grado 1 sin cambios
for s,p,o in g1:
  print(s,p,o)

#Solucion del problema
clase_persona="http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
clase="http://data.org"
clase_persona_g1=[]
for s,p,o in g1:
  if clase in o:
    clase_persona_g1.append(s)

FOAF = Namespace("http://xmlns.com/foaf/0.1/")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")

for s,p,o in g2:
  if s in clase_persona_g1:
    g1.add((s,p,o))

#Solucion
print("\tGrafo 1:")
for s,p,o in g1:
  print(s,p,o)

print("\tGrafo 2:")
for s,p,o in g2:
  print(s,p,o)