# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VcS4mqWxP5AxKgNfuVSnZidFW1FJTsg7

**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.namespace import OWL
clase1="http://data.three.org"
clase2="http://data.four.org"

individuos1=[]
for s,p,o in g1:
  if clase1 in o:
    individuos1.append(s)

individuos2=[]
for s,p,o in g2:
  if clase2 in o:
    individuos2.append(s)

for individuo in individuos1:
  for individuo2 in individuos2:
    familiaURI=URIRef("http://www.w3.org/2001/vcard-rdf/3.0#Family")
    givenURI=URIRef("http://www.w3.org/2001/vcard-rdf/3.0#Given")
    igual_name_familia=g1.value(subject=individuo,predicate=familiaURI) == g2.value(subject=individuo2,predicate=familiaURI)
    igual_name_given=g1.value(subject=individuo,predicate=givenURI) == g2.value(subject=individuo2,predicate=givenURI)
    if igual_name_familia and igual_name_given:
      g3.add((individuo,OWL.sameAs,individuo2))

#Solucion del problema
for s,p,o in g3:
  print(s,p,o)

print("\tGrado 1:")
for s,p,o in g1:
  print(s,p,o)
print("\tGrado 2:")
for s,p,o in g2:
  print(s,p,o)