# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/mohamed-khachani/Curso2025-2026-DataScience/blob/master/Assignment4/course_materials/notebooks/Task09.ipynb

**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.namespace import OWL

query1 = """
SELECT ?p ?g ?f WHERE {
  ?p a <http://data.three.org#Person>.
  ?p <http://www.w3.org/2001/vcard-rdf/3.0#Given>  ?g .
  ?p <http://www.w3.org/2001/vcard-rdf/3.0#Family> ?f .
}
"""

query2 = """
SELECT ?p ?g ?f WHERE {
  ?p a <http://data.four.org#Person>.
  ?p <http://www.w3.org/2001/vcard-rdf/3.0#Given>  ?g .
  ?p <http://www.w3.org/2001/vcard-rdf/3.0#Family> ?f .
}
"""

idx_g1 = {}
for row in g1.query(query1):
  idx_g1[f"{row.g}_{row.f}"] = row.p

for row2 in g2.query(query2):
  if idx_g1.get(f"{row2.g}_{row2.f}"):
    g3.add((row2.p, OWL.sameAs, idx_g1[f"{row2.g}_{row2.f}"]))

#for s, p, o in g3:
#  print(s,p,o)